use serde::{Deserialize, Serialize};

/// Represents an advanced hardware property of a physical network adapter.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct NicAdvancedProperty {
    #[serde(rename = "DisplayName")]
    pub display_name: String,
    #[serde(rename = "RegistryKeyword")]
    pub registry_keyword: String,
    #[serde(rename = "RegistryValue")]
    pub registry_value: Option<Vec<String>>,
}

impl NicAdvancedProperty {
    /// Helper to get the first registry value as a string slice.
    pub fn first_value(&self) -> Option<&str> {
        self.registry_value.as_ref().and_then(|v| v.first().map(|s| s.as_str()))
    }
}

/// Backup record for an individual adapter property prior to modification,
/// enabling 100% deterministic rollback.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct AdapterPropertyBackup {
    pub adapter_name: String,
    pub keyword: String,
    pub display_name: String,
    pub original_value: String,
}

/// Status of 802.3x Flow Control on the network adapter.
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
pub enum FlowControlSetting {
    Disabled = 0,
    TxEnabled = 1,
    RxEnabled = 2,
    RxTxEnabled = 3,
    Unknown = -1,
}

impl From<i32> for FlowControlSetting {
    fn from(val: i32) -> Self {
        match val {
            0 => FlowControlSetting::Disabled,
            1 => FlowControlSetting::TxEnabled,
            2 => FlowControlSetting::RxEnabled,
            3 => FlowControlSetting::RxTxEnabled,
            _ => FlowControlSetting::Unknown,
        }
    }
}

/// Comprehensive verification result for Receive Side Scaling (RSS).
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct RssVerificationResult {
    pub adapter_name: String,
    pub rss_enabled: bool,
    pub global_tcp_rss_enabled: bool,
    pub num_queues: u32,
    pub meets_minimum_queues: bool,
    pub is_optimal: bool,
    pub recommendations: Vec<String>,
}

/// Details of a registered Windows QoS DSCP policy.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct QosPolicyInfo {
    pub name: String,
    pub app_path_name: String,
    pub protocol: String,
    pub dscp_value: u8,
    pub dst_port_start: u16,
    pub dst_port_end: u16,
    pub is_active: bool,
}

/// Rollback record for a QoS policy and associated registry settings.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct QosPolicyBackup {
    pub policy_name: String,
    pub previous_nla_setting: Option<String>,
    pub was_policy_present_before: bool,
}

/// Standard Bufferbloat Grade (Bufferbloat.net / Flent grading scale).
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
pub enum BufferbloatGrade {
    APlus,
    A,
    B,
    C,
    D,
    F,
}

impl BufferbloatGrade {
    pub fn from_latency_delta(delta_ms: f64, packet_loss_pct: f64) -> Self {
        if packet_loss_pct > 5.0 {
            return BufferbloatGrade::F;
        }
        if delta_ms < 5.0 {
            BufferbloatGrade::APlus
        } else if delta_ms < 15.0 {
            BufferbloatGrade::A
        } else if delta_ms < 30.0 {
            BufferbloatGrade::B
        } else if delta_ms < 60.0 {
            BufferbloatGrade::C
        } else if delta_ms < 120.0 {
            BufferbloatGrade::D
        } else {
            BufferbloatGrade::F
        }
    }

    pub fn as_str(&self) -> &'static str {
        match self {
            BufferbloatGrade::APlus => "A+",
            BufferbloatGrade::A => "A",
            BufferbloatGrade::B => "B",
            BufferbloatGrade::C => "C",
            BufferbloatGrade::D => "D",
            BufferbloatGrade::F => "F",
        }
    }
}

/// Full diagnostic report generated by the Bufferbloat & Network Health Runner.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct BufferbloatReport {
    pub unloaded_ping_ms: f64,
    pub unloaded_jitter_ms: f64,
    pub loaded_ping_ms: f64,
    pub loaded_jitter_ms: f64,
    pub bufferbloat_delta_ms: f64,
    pub grade: BufferbloatGrade,
    pub packet_loss_pct: f64,
    pub target_host: String,
    pub test_duration_secs: f64,
    pub recommendations: Vec<String>,
}
