[package]
name = "val-opt-gui"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
val-opt-shared = { path = "../val-opt-shared" }
val-opt-core = { path = "../val-opt-core" }
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
anyhow.workspace = true
thiserror.workspace = true
slint.workspace = true

[build-dependencies]
slint-build.workspace = true

[target.'cfg(windows)'.dependencies]
windows.workspace = true
